"""DOCX export for typed Catalyst AI artifacts."""
from io import BytesIO
from docx import Document
from catalyst_ai.ai.schemas import GeneratedArtifact, ProductRequirementsDocument, TechnicalSpecification, UserStoryArtifact


def _bullets(document: Document, values: list[str]) -> None:
    for value in values:
        document.add_paragraph(value, style="List Bullet")


def _section(document: Document, heading: str, value: str | list[str]) -> None:
    document.add_heading(heading, level=2)
    if isinstance(value, list):
        _bullets(document, value) if value else document.add_paragraph("None identified.")
    else:
        document.add_paragraph(value or "None identified.")


def build_artifact_docx(artifact: GeneratedArtifact) -> bytes:
    """Build an in-memory professional DOCX without exposing internal source hashes."""
    if not isinstance(artifact, GeneratedArtifact):
        raise ValueError("A generated artifact is required for DOCX export.")
    document = Document()
    content = artifact.content
    document.add_heading(content.title or artifact.metadata.artifact_type.value, level=1)
    document.add_paragraph(f"Artifact Type: {artifact.metadata.artifact_type.value}")
    document.add_paragraph(f"Stakeholder Perspective: {artifact.metadata.stakeholder}")
    document.add_paragraph(f"Context Source: {artifact.metadata.context_source}")
    document.add_paragraph("Generated by Catalyst AI")
    if isinstance(content, ProductRequirementsDocument):
        for heading, value in (("Executive Summary", content.executive_summary), ("Problem Statement", content.problem_statement), ("Business Objectives", content.business_objectives), ("Target Users", content.target_users), ("Personas", content.personas), ("In Scope", content.in_scope), ("Out of Scope", content.out_of_scope), ("Functional Requirements", content.functional_requirements), ("Non-functional Requirements", content.non_functional_requirements), ("Dependencies", content.dependencies), ("Risks", content.risks), ("Assumptions", content.assumptions), ("Success Metrics", content.success_metrics), ("Open Questions", content.open_questions)):
            _section(document, heading, value)
    elif isinstance(content, UserStoryArtifact):
        _section(document, "Overview", content.overview)
        document.add_heading("User Stories", level=2)
        for story in content.stories:
            document.add_heading(f"{story.id} — {story.title}", level=3)
            document.add_paragraph(story.story)
            document.add_paragraph(f"Priority: {story.priority}")
            _section(document, "Acceptance Criteria", story.acceptance_criteria)
            _section(document, "Dependencies", story.dependencies)
            _section(document, "Notes", story.notes)
        for heading, value in (("Cross-cutting Requirements", content.cross_cutting_requirements), ("Assumptions", content.assumptions), ("Open Questions", content.open_questions)):
            _section(document, heading, value)
    elif isinstance(content, TechnicalSpecification):
        for heading, value in (("Solution Overview", content.solution_overview), ("Architecture Summary", content.architecture_summary), ("Architecture Components", content.architecture_components), ("Integrations", content.integrations), ("API Requirements", content.api_requirements), ("Data Requirements", content.data_requirements), ("Security Requirements", content.security_requirements), ("Non-functional Requirements", content.non_functional_requirements), ("Deployment Considerations", content.deployment_considerations), ("Observability Requirements", content.observability_requirements), ("Dependencies", content.dependencies), ("Technical Risks", content.technical_risks), ("Assumptions", content.assumptions), ("Open Decisions", content.open_decisions)):
            _section(document, heading, value)
    else:  # pragma: no cover - protects future schema additions
        raise ValueError("Unsupported artifact content for DOCX export.")
    output = BytesIO(); document.save(output); return output.getvalue()
