"""DOCX export for typed Catalyst AI artifacts."""
from io import BytesIO
from docx import Document
from pydantic import BaseModel
from catalyst_ai.ai.schemas import GeneratedArtifact

def _label(name: str) -> str: return name.replace("_", " ").title()
def _value(value) -> str:
    if isinstance(value, list): return "; ".join(_value(x) for x in value if _value(x))
    if isinstance(value, BaseModel): return "; ".join(f"{_label(k)}: {_value(v)}" for k,v in value.model_dump().items() if v not in ("", [], None))
    return str(value).strip()
def add_optional_paragraph(document, label, value):
    text=_value(value)
    if text: document.add_paragraph(f"{label}: {text}")
def add_bullet_list(document, values):
    for value in values:
        text=_value(value)
        if text: document.add_paragraph(text, style="List Bullet")
def add_traceability(document, values):
    if values: add_bullet_list(document, [f"{x.source_type}: {x.reference}" for x in values])
def _section(document, heading, value):
    if not value: return
    document.add_heading(heading, level=2)
    if isinstance(value, str): document.add_paragraph(value)
    elif isinstance(value, list):
        for item in value:
            if isinstance(item, BaseModel):
                data=item.model_dump(); title=data.pop("id", "") or next((str(v) for k,v in data.items() if k not in {"traceability"} and isinstance(v,str) and v), "Item")
                document.add_heading(title, level=3)
                for key,val in data.items():
                    if key == "traceability":
                        if val: document.add_heading("Traceability",level=4); add_bullet_list(document,[f"{x.get('source_type','Product Understanding')}: {x.get('reference','')}" for x in val])
                    elif val not in ("", [], None): add_optional_paragraph(document,_label(key),val)
            else: document.add_paragraph(str(item), style="List Bullet")
def build_artifact_docx(artifact: GeneratedArtifact) -> bytes:
    if not isinstance(artifact, GeneratedArtifact): raise ValueError("A generated artifact is required for DOCX export.")
    document=Document(); content=artifact.content
    document.add_heading(content.title or artifact.metadata.artifact_type.value,level=1)
    document.add_paragraph(f"Artifact Type: {artifact.metadata.artifact_type.value}"); document.add_paragraph(f"Stakeholder Perspective: {artifact.metadata.stakeholder}"); document.add_paragraph(f"Context Source: {artifact.metadata.context_source}"); document.add_paragraph("Generated by Catalyst AI")
    for name,value in content.model_dump().items():
        if name not in {"title","document_version"} and value not in ("",[],None): _section(document,_label(name),getattr(content,name))
    output=BytesIO(); document.save(output); return output.getvalue()
